export const copy = {
  "no": {
    "unknown": "Ukjent",
    "legends": "sagn",
    "types": "sagntyper",
    "exploreTopic": "Utforsk hele temaet",
    "exploreType": "Utforsk sagn",
    "found": "typer vist",
    "dashboard": "Statistikk",
    "allTopics": "Alle temaer",
    "counties": "Fylker",
    "collectors": "Samlere",
    "years": "Innsamlingsår",
    "undated": "udaterte",
    "topicsChart": "Hvor mange sagn finnes i hvert tema?",
    "dashboardHint": "Velg et tema for å se sagntypene. Velg deretter en type for å se hvor, når og av hvem sagnene ble samlet.",
    "ofCollection": "av samlingen",
    "typesChart": "Sagntyper i dette temaet",
    "sort": "Sorter etter",
    "most": "Flest opptegnelser",
    "code": "ML-kode",
    "typeHint": "Velg en type for å undersøke dens fordeling, eller åpne sagnene direkte i sagnutforskeren.",
    "ofTopic": "av temaet",
    "noDates": "Ingen innsamlingsår er oppgitt.",
    "coverage": "Hvor er variantene registrert?",
    "people": "Hvem samlet dem?",
    "dates": "Når ble sagnene samlet?",
    "dateHint": "Opptegnelser fordelt på tiår. Udaterte sagn vises separat.",
    "dated": "med innsamlingsår",
    "metadata": "Metadata som mangler",
    "missingCounty": "Uten fylke",
    "missingCollector": "Uten kjent samler",
    "missingNarrator": "Uten kjent informant",
    "datasetNote": "ML 6070 beholdes som én type slik den er registrert i datasettet. Den er ikke fordelt på 6070A eller 6070B.",
    "dashboardTitle": "Samlingen gjennom temaer",
    "distributionNote": "Tallene gjelder opptegnelser i denne samlingen.",
    "goExplorer": "Åpne i sagnutforskeren",
    "share": "Kopier lenke",
    "viewLabel": "Visning av ML-indeksen",
    "searchPlaceholder": "Søk etter ML-kode, tema eller tittel…",
    "copied": "Lenke kopiert",
    "copyFailed": "Kopier adressen fra nettleseren.",
    "eyebrow": "Vandresagn · en inngang til samlingen",
    "title": "ML-indeks",
    "intro": "Finn beslektede sagn gjennom temaer og typer.",
    "records": "opptegnelser",
    "about": "Hva er en ML-type?",
    "contents": "Innholdsfortegnelse",
    "contentsTitle": "Finn sagn gjennom innholdsfortegnelsen",
    "contentsHint": "Åpne et tema og velg en type. Sagnene åpnes i sagnutforskeren, der du kan lese, søke og filtrere videre.",
    "searchLabel": "Søk etter kode eller tittel",
    "expandAll": "Åpne alle temaer",
    "collapseAll": "Lukk alle",
    "empty": "Ingen typer funnet. Prøv en annen kode eller tittel.",
    "methodEyebrow": "En nøkkel til materialet",
    "methodTitle": "Les typer gjennom variantene",
    "method": "ML står for The Migratory Legends, Reidar Th. Christiansens katalog fra 1958, senere utvidet av Inger Christiansen. En type samler beslektede fortellinger etter motiv. Den er et redskap for å finne og sammenligne varianter.",
    "source": "Om typekatalogen hos SAMLA"
  },
  "en": {
    "unknown": "Unknown",
    "legends": "legends",
    "types": "legend types",
    "exploreTopic": "Explore the whole topic",
    "exploreType": "Explore legends",
    "found": "types shown",
    "dashboard": "Statistics",
    "allTopics": "All topics",
    "counties": "Counties",
    "collectors": "Collectors",
    "years": "Collection years",
    "undated": "undated",
    "topicsChart": "How many legends are in each topic?",
    "dashboardHint": "Choose a topic to see its legend types. Then choose a type to see where, when and by whom its legends were collected.",
    "ofCollection": "of the collection",
    "typesChart": "Legend types in this topic",
    "sort": "Sort by",
    "most": "Most records",
    "code": "ML code",
    "typeHint": "Choose a type to investigate its distribution, or open its legends directly in the legend explorer.",
    "ofTopic": "of the topic",
    "noDates": "No collection years are recorded.",
    "coverage": "Where were variants recorded?",
    "people": "Who collected them?",
    "dates": "When were the legends collected?",
    "dateHint": "Records grouped by decade. Undated records are shown separately.",
    "dated": "with a collection year",
    "metadata": "Missing metadata",
    "missingCounty": "Without a county",
    "missingCollector": "Without a known collector",
    "missingNarrator": "Without a known narrator",
    "datasetNote": "ML 6070 remains a single type as recorded in the dataset. It is not assigned to 6070A or 6070B.",
    "dashboardTitle": "The collection by topic",
    "distributionNote": "Counts refer to records in this collection.",
    "goExplorer": "Open in legend explorer",
    "share": "Copy link",
    "viewLabel": "ML index view",
    "searchPlaceholder": "Search by ML code, topic or title…",
    "copied": "Link copied",
    "copyFailed": "Copy the address from your browser.",
    "eyebrow": "Migratory legends · a way into the collection",
    "title": "ML Index",
    "intro": "Find related legends by topic and type.",
    "records": "records",
    "about": "What is an ML type?",
    "contents": "Table of contents",
    "contentsTitle": "Find legends in the table of contents",
    "contentsHint": "Expand a topic and choose a type. The legends open in the legend explorer, where you can read, search and filter further.",
    "searchLabel": "Search by code or title",
    "expandAll": "Expand all topics",
    "collapseAll": "Collapse all",
    "empty": "No types found. Try another code or title.",
    "methodEyebrow": "A key to the material",
    "methodTitle": "Read types through their variants",
    "method": "ML means The Migratory Legends, Reidar Th. Christiansen’s 1958 catalogue, later expanded by Inger Christiansen. A type groups related stories by motif and helps readers find and compare variants.",
    "source": "About the type catalogue at SAMLA"
  }
};
